### ISSUE TITLE
OSDeploy - Support for Windows 10 Enterprise LTSC 2021

### ISSUE THREAD

**Issue by fraser-simon** [OSDeploy/OSD#105]
I would like to use OSDeploy to update LTSC21 which is based on Windows 10 21H2, but it seems not to be recognised as a supported OS .

Could you possibly add it to the list of supported OS

We base all our dektop images on LTSC because its long support cycle and less frequent changes, fits well with the regulatory framewok we operate under as a health service provider

**Comment by gwblok** [comment]
I'm not against this request, but I have no way to develop it / test it

So currently, you're downloading LTSC21 from Microsoft, placing the WIM or ISO on the OSDCloudUSB in the OS folder, but the OS does't show up as an option to install?

**Comment by fraser-simon** [comment]
Sorry I may have missunder stood what this tool is _for. I'm not using an OSDCLoudUSB. Im trying to build a custom windows depoyment using MDT. I was follwing advice from another wed site that sugested, 

"When adding operating system images, always try to use a media that is already updated by Microsoft, 
or by you using the OSD Builder community tool. This way you don’t need to install software updates 
during build and capture, which will save some time"

So I downloaded your module and folowed instructions here https://osdbuilder.osdeploy.com/docs/osimport/import-osmedia-buildnetfx making what I thought were appropriate chages

First I mounted my MS ISO as the E: drive, then ran 
Import-OSMedia -ImageName "Windows 10 Enterprise" -SKipGrid -Update -BuildNetFX
The result was

PS C:\Windows\system32> Import-OSMedia -ImageName "Windows 10 Enterprise" -SKipGrid -Update -BuildNetFX
========================================================================================
Import-OSMedia BEGIN
2024-01-11-220657 Get-OSDBuilder: Validating OSDBuilder Content
2024-01-11-220657 WARNING: This version of OSDBuilder only supports:
2024-01-11-220657 WARNING: Windows 10 1607 - 21H2
2024-01-11-220657 WARNING: Windows 11 21H2 - 22H2
2024-01-11-220657 WARNING: Windows Server 2016 1607 - Windows Server 2022 21H1
========================================================================================
2024-01-11-220657 Media: Scan E:\Sources\install.wim
ImageIndex 1: Windows 10 Enterprise LTSC
ImageIndex 2: Windows 10 Enterprise N LTSC
========================================================================================
2024-01-11-220700 WARNING: Import-OSMedia: OSMedia was not found . . . Exiting!
PS C:\Windows\system32>

Which I tool to mean that the ISO was not supported.

However this evening I revisited your site and thought I might try
Import-OSMedia -ImageName "Windows 10 Enterprise LTSC" -SKipGrid -Update -BuildNetFX
and that seems to have worked.

So I may have solved my own problem.

However some of the identified updates failed to apply so perhaps this isnt going to do what I want.

Regards

**Comment by gwblok** [comment]
Yeah, sorry, I was thinking you were talking about OSDCloud vs OSDBuilder.
I haven't done any work with LTSC and OSDBuilder either.  

Good luck!  Happy OS Deploying!
