### ISSUE TITLE
Possible bug in Save-FeatureUpdate.ps1

### ISSUE THREAD

**Issue by JHBDO** [OSDeploy/OSD#106]
**Describe the bug**
I was trying to call the Save-FeatureUpdate function, but it kept coming back with the 'Could not verify an Internet connection for the Feature Update' message.  In looking at the code in that function, it appears that the Test-WebConnection command is using $GetFeatureUpdate.FileUri, but FileUri is not a property of $GetFeatureUpdate.  However, Url is.  I'm assuming maybe this changed when the method for downloading the .esd file was changed recently?  This was using v24.1.11.1.

**To Reproduce**
1. Save-FeatureUpdate -DownloadPath "C:\temp" -OSName 'Windows 11 23H2 x64' -OSActivation Retail -OSLanguage en-us -OSArchitecture x64
2. Get 'Could not verify an Internet connection' message.

**Expected behavior**
Test-WebConnection should return $true, and Save-WebFile should download the ESD to the $DownloadPath folder.

![save-featureupdate](https://github.com/OSDeploy/OSD/assets/44410295/cc1e5f6a-6d9f-4e25-a176-d37dcedfc056)

**Comment by gwblok** [comment]
Thank you.
You are completely correct, when we changed process to find feature update ESD files, this reference was missed.
GitHub has been updated, so next time the module is released, it will have the fix incorporated.
