### ISSUE TITLE
SetupComplete Phase - Import from any Drive

### ISSUE THREAD

**Issue by MichaelEscamilla** [OSDeploy/OSD#107]
**Is your feature request related to a problem? Please describe.**
Update the new 'SetupComplete Phase' from 24.1.3.1 to copy from any drive that has the folder '<DriveLetter>:\OSDCloud\Scripts\SetupComplete' instead of just from a USB instance of OSDCloud.

**Describe the solution you'd like**
Update the new 'SetupComplete Phase' from 24.1.3.1 to copy from any drive that has the folder '<DriveLetter>:\OSDCloud\Scripts\SetupComplete' instead of just from a USB instance of OSDCloud.

**Describe alternatives you've considered**
Nothing at the moment.

**Additional context**
Something similar to 'Automated Path' https://www.osdcloud.com/osdcloud-automate/basic-configuration#automate-paths for storing the 'SetupComplete' folder so that it'll be copied to the ISO or USB when building those.

for importing, something similar to the https://github.com/OSDeploy/OSD/blob/05b482594734162d04e296596cc3ca5eb48334c5/Public/Start-OSDCloudGUI.ps1#L85 or https://github.com/OSDeploy/OSD/blob/05b482594734162d04e296596cc3ca5eb48334c5/Public/OSDCloud.ps1#L455 sections that look for the config files on any drive with the correct OSDCloud path.

**Comment by gwblok** [comment]
I'm planning to make it so OSDCloud will check the OSDCloudUSB in a specific location, which is the current behavior, but add the detection if: C:\OSDCloud\Scripts\SetupComplete\SetupComplete.cmd exists to run it.

**Comment by MichaelEscamilla** [comment]
When you say also check the C:\OSDCLOUD are you talking about the computer you're using to build you OSDCloudUSB/ISO?

Because if you are running OSDCloud, C: won't existing until the image is applied. Which meansnitnwould need to check X:\ or other drives when you're in WINPE.

Unless I'm misunderstanding what you are PLANNING, or how it is currently implemented.

**Comment by gwblok** [comment]
It will check C: on the device it is building.
So basically my assumption is that you're scripting OSDCloud and after it finishes the WinPE phase, instead of having OSDCloud auto reboot, you have your script copy or build your custom Setup Complete files on C, then trigger your own reboot to have it continue.

**Comment by MichaelEscamilla** [comment]
Maybe I just don't understand how it works right now, so I'll take your word for it. because it seems like you have worked out in your head. I'll do some testing with the way you have it now to get a better understanding and maybe have a better perspective on it, and reply again.

Because if I have a Folder 'SetupComplete' with my SetupComplete.cmd and SetupComplete.ps1, it would be nice to just have it stored in my Workspace so that it'll always be copied to my ISO or USB when building those. That way OSDCloud will always copy it over and we won't have to run a script to create the files.


>  instead of having OSDCloud auto reboot, you have your script copy or build your custom Setup Complete files on C, then trigger your own reboot to have it continue.

So after OSDCloud runs and doesn't reboot, my script would then create the SetupComplete Folder and Files? Because at this point the Invoke-OSDCloud function is done running and wouldn't automatically copy those files over and add the commands to run.

**Comment by gwblok** [comment]
You can create the SetupComplete folder in your workspace, and it will copy over to the USB Drive too
![image](https://github.com/OSDeploy/OSD/assets/26312309/c210c717-5e7e-4841-8d74-aa6699a8d429)

If you have your OSDCloud USB connected, you can also run this command to create a generic set of files for you:
New-OSDCloudUSBSetupCompleteTemplate

I'll look into having it auto create a generic set as well when you create a new workspace, I do like that idea.  When time allows.

**Comment by gwblok** [comment]
Note, the next release will add this function: New-OSDCloudWorkSpaceSetupCompleteTemplate
That will create the two generic files in your Workspace.

**Comment by gwblok** [comment]
@MichaelEscamilla, I hope this is all making sense.  Let me know if you need any more assistance on this.  I'm closing for now.

**Comment by muzzar78** [comment]
@gwblok @MichaelEscamilla I have just started using OSDCloud and love the project. I think I came across the same problem Michael was referring to when he created this issue. I have created a custom SetupComplete script under my workspace\Config\Scripts\SetupComplete and when I run Update-OSDCloudUSB the scripts get copied to my usb drive. However when I run Edit-OSDCloudWinPE -StartOSDCloudGUI they don't get copied to the ISO. So when I'm testing on a vm vs using a usb with a physical device I get a different experience.

@gwblok Based on your comments, it sounds like the approach your suggesting would be to create a script in workspace\Config\Scripts\Shutdown that copied the SetupComplete scripts to the c drive as part of the Invoke-OSDCloud process. I will give this a try.

I was thinking this section of OSDCloud.ps1 could be modified to check the drives.

https://github.com/OSDeploy/OSD/blob/1cfee1874f531b2440946599923399e1d21840fc/Public/OSDCloud.ps1#L2245C5-L2255C6

Something like this.

```
    #Checks for SetupComplete.cmd file on USB Drive, if finds one, sets OSD process to run the SetupComplete
    #Flashdrive\OSDCloud\Config\Scripts\SetupComplete
    if (Get-SetupCompleteOSDCloudUSB -eq $true){
        Set-SetupCompleteOSDCloudUSB
    }
    #Makes it so that if SetupComplete finds C:\OSDCloud\Scripts\SetupComplete\SetupComplete.cmd, it will run it.
    else{
        Set-SetupCompleteOSDCloudCustom
        #region ----- If there are SetupComplete scripts in WinPE then copy them to C:\OSDCloud\Scripts\SetupComplete
        $WinPeSetupComplete = Get-PSDrive -PSProvider FileSystem | Where-Object {$_.Name -ne 'C'} | ForEach-Object {
            Get-ChildItem "$($_.Root)OSDCloud\Config\Scripts\SetupComplete" -File -Recurse -Force -ErrorAction Ignore
        }
        if ($WinPeSetupComplete) {
            Write-SectionHeader '[i] WinPE SetupComplete'
            foreach ($Item in $WinPeSetupComplete) {
                Write-DarkGrayHost "$($Item.FullName)"
                $null = Copy-Item -Path $Item.FullName -Destination "C:\OSDCloud\Scripts\SetupComplete\$($Item.Name)" -Force -ErrorAction Ignore
            }
        }
        #endregion
    }
```

**Comment by gwblok** [comment]
Sorry for delay, haven't been monitoring this lately.

You will not want to create your own setup complete files, OSDCloud creates them automatically during the process.  If you create one, you'll overwrite what is there.

OSDCloud will grab a custom setup complete script on your flash drive and run it as part of the process.

You just have to create it in a specific place in your OSDCloud workspace so it gets copied to the correct place in your flash drive.  There are functions to create templates for you already.

During OSDCloud process, it will check your flash drive in a specific location then copy it to c: OSDCloud folder in the correct location.

Sorry I don't have details, I'm sitting in my car as I write this.  If you want the specifics, they are in the code. Search for SetupComplete in the main OSD function to see when it applies during the process, and search the repo for SetupComplete and look for a function with the work template
