### ISSUE TITLE
How do i force clear firmware updates

### ISSUE THREAD

**Issue by Abe-Telo** [OSDeploy/OSD#111]
I am having a issue after using the usb for a few installs, at times, upon going to the next PC, it attempts to do firmware updates but fails, it goes on a loop and I cannot boot into USB. Is there away to clear this behavior from looping. This only happened when USB is plugged in. 

Surface models

**Comment by gwblok** [comment]
I don't do any testing on Surface Devices, so you might be better off asking for help in another community forum where people use Surface Devices.

I'll leave this open for a bit to see if anyone else who might monitor this thread can assist.  I'll loop back in a couple weeks and close it.
