### ISSUE TITLE
Getting: PS>TerminatingError(): "System error." in setupcomplete.ps1

### ISSUE THREAD

**Issue by StevenVBeek** [OSDeploy/OSD#115]
[HP EliteBook 840 14 inch G9 Notebook PC.json](https://github.com/OSDeploy/OSD/files/14373295/HP.EliteBook.840.14.inch.G9.Notebook.PC.json)
[HP Image Assistant.log](https://github.com/OSDeploy/OSD/files/14373296/HP.Image.Assistant.log)
[HPIACustomLog.log](https://github.com/OSDeploy/OSD/files/14373297/HPIACustomLog.log)
[HP.JSON](https://github.com/OSDeploy/OSD/files/14373298/HP.JSON)
[SetupComplete.log](https://github.com/OSDeploy/OSD/files/14373299/SetupComplete.log)
**Describe the bug**

**To Reproduce**
Enable: HPIAFirmware = $true

**Expected behavior**
I think when there are no recommendation the scripts just need to be finished without Exit 0 .

**Screenshots**
see logs.

**Desktop (please complete the following information):**
 - OS: Win11 
 - Version 23H2

**Additional context**
In the Invoke-HPIA function, if there's an exit code of 257, it will trigger an exit with code 0. This action halts the execution of the entire setupcomplete.ps1 script, preventing any settings from running after the firmware is invoked.

@gwblok can we remove the Exit 0 if that is they issue (also for exitcode 256)? Line 247 in Invoke-HPIA.ps1

**Comment by gwblok** [comment]
Yes, thank you, I missed those earlier.
Done.
Code is updated on GitHub, will be part of next OSD Module Release
