### ISSUE TITLE
Custom URL for custom WIM files with OSDCloudGUI (online method)

### ISSUE THREAD

**Issue by trongtinh1212** [OSDeploy/OSD#121]
Hi, your project is great, thanks alot
I already read the whole documents, i would like to use the custom wim files that i hosting on some urls, i will use it to download and install instead of using esd files downloaded from MS. Do we have any solutions for this ?

**Comment by trongtinh1212** [comment]
> Start-OSDCloud -FindImageFile
> 
> 
> 
> ![image](https://github.com/OSDeploy/OSD/assets/44706641/5743b4fe-e4a1-4702-8877-e808149063c6)
> 
> 

Yes i can do it with Start-OSDCloud, i mean how to use it with Start-OSDCloudGUI

**Comment by AkosBakos** [comment]
Check please the following issues which are already solved/closed:
https://github.com/OSDeploy/OSD/issues/112
https://github.com/OSDeploy/OSD/issues/108
https://github.com/OSDeploy/OSD/issues/39

**Comment by trongtinh1212** [comment]
@AkosBakos thank you, i can manage it now with -StartURL
