### ISSUE TITLE
Unable to add HP drivers into the WinPE

### ISSUE THREAD

**Issue by JorgaWetzel** [OSDeploy/OSD#126]
﻿With the build 24.3.10.1, it is no longer possible to integrate the HP drivers into the WinPE.
﻿﻿![image](https://github.com/OSDeploy/OSD/assets/51820881/0bfec073-ff0b-433e-a0d5-038301753679)

**Comment by gwblok** [comment]
Just some notes as I look into this.

Issue reproduced.

Following the Functions:
Edit-OSDCloudWinPE -> Save-WinPECloudDriver -> Get-HpWinPEDriverPack

Get-HPWinPEDriverPack leverages this URL:
$DriverPackInfoUrl = $Global:OSDModuleResource.WinPEDriverPack.HP.Info
which is: http://ftp.ext.hp.com/pub/caps-softpaq/cmit/softpaq/WinPE10.html

The function then tries to grab the softpaq exe from the links on the page.
it would appear HP slightly modified the URL pre-fix.

Current Code was looking for: '*ftp.hp.com/pub/softpaq/*/*.exe'
However, HP added .ext into it (ftp.ext.hp.com)

I'm going to modify the function to be *.hp.com, which resolves the issue.

@OSDeploy, do you see any issue with that?  

Change is pushed to GitHub

![image](https://github.com/OSDeploy/OSD/assets/26312309/ec4e51fe-0461-4b91-a19b-8c568ce87ac0)

Also adding a little verbose logging into the functions.

**Comment by gwblok** [comment]
Note, tests with updated functions worked successfully.  
Test Steps:

- Replaced updated Functions (PS Scripts) in local Module
- Imported the Updated Module
- Created new OSDCloud WorkSpace with Generic WinPE
- Ran PS> Edit-OSDCloudWinPE -CloudDriver HP

![image](https://github.com/OSDeploy/OSD/assets/26312309/0e135eeb-1e1f-4027-9109-2736a1643570)
![image](https://github.com/OSDeploy/OSD/assets/26312309/f7b9735b-e7d6-4c93-85eb-f5c8cb3d7d8d)



Edit-OSDCloudWinPE -CloudDrivers 'HP' -Verbose will return quite a bit of helpful information in troubleshooting.

Next time the module is updated, the fix will be included.

**Comment by gwblok** [comment]
Tested this morning with updated Module, it worked without issue.  Closing Issue

**Comment by JorgaWetzel** [comment]
Thank you, I can confirm that the issue has been resolved on my end as well. You are doing an amazing job with this project, many THANKS.
