### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by StevenVBeek** [OSDeploy/OSD#135]
Hi @gwblok  @OSDeploy 

I saw that script: Invoke-Expression'https://raw.githubusercontent.com/OSDeploy/OSD/master/cloud/modules/_winpe.psm1

is not there anymore. This link is hardcoded in: https://github.com/OSDeploy/OSD/blob/master/Public/OSDCloudTS/Set-SetupCompleteCreateStart.ps1

line 32

**Comment by gwblok** [comment]
Thanks, I've just disabled that line for now, a quick review leads me to believe I don't need anything from that anyway.
