### ISSUE TITLE
Windows 11 23H2 Get-WindowsImage: The data is invalid

### ISSUE THREAD

**Issue by BMerner** [OSDeploy/OSD#136]
When using OSDCloud to install Windows11 23H2 - OSD cloud errors the installation. Using the default OSDCloudGUI. I've tested using Pro, Enterprise, Volume/retail. en-us, en-GB. the outcome is the same. 

When the script runs the Get-WindowsImage it returns erro data is invalid, which then in turn makes the subsequent commands fail.

The same media and process works fine if choosing a Windows 10 installation. I've tested the install on multiple devices both physical and virtual. This is a new OSD workspace, using the default options.

In order to troubleshoot, I setup a new system and re-provisioned OSD and recreated the USB/ISO same issue occurs.

**Screenshots**
![IMG_8682](https://github.com/OSDeploy/OSD/assets/166634705/bca3f7fd-699c-46f4-b201-f3d9357415ca)

**Comment by BMerner** [comment]
Sorry forgot to mention 22H2 Windows 11 Installs fine also, its specifically 23H2.

**Comment by gwblok** [comment]
if I was a betting man, I'd guess your downloads are getting messed up along the way and you're not actually getting the correct download.

Do me a favor, grab that ESD file, place it on your Flash Drive, then do a hash check on it.

I just ran OSDCloud on my VM, and all was well


How to get the Hash:

```PowerShell
$OS = Get-OSDCloudOperatingSystems
$Test = $OS | Where-Object {$_.Name -match "Windows 11 23H2" -and $_.Architecture -eq 'x64' -and $_.Language -eq "en-us" -and $_.Activation -eq "Retail"}

$Hash = $Test.SHA1
```

![image](https://github.com/OSDeploy/OSD/assets/26312309/6b9acb75-f714-4df8-b5ab-65c36fe1909b)

Then you can grab the SHA1 has from the ESD file you downloaded

```
Get-FileHash $ImagePath -Algorithm SHA1
```

Thanks, it sure seems like there is something that is breaking your downloads.

**Comment by BMerner** [comment]
Looks like you should place that bet! 
I setup a clean usb on another network and the 11 23H2 install worked fine, how odd that just that file download is having issues on my network. Thanks for feeding back.
