### ISSUE TITLE
Start-OSDCloudGUI on HP Elitebook 860 G11

### ISSUE THREAD

**Issue by mds-bladt** [OSDeploy/OSD#140]
**Describe the bug**
Unable to use WinPE usb on HP Elitebook 860 G11
It never starts the gui if you have you WinPE start the gui automatically.
If i am trying to run the cmd in a powershell window, it comes with an error: Unable to retrieve BIOS data for a platform with ID 8C26 (data file not found)
It seems to relate to the HP.ClientMangement module

**To Reproduce**
Use powershell windows in WinPE usb environment, Start-OSDCloudGUI on HP Elitebook 860 G11

**Expected behavior**
OSDCloud Gui should start

**Screenshots**
![image](https://github.com/OSDeploy/OSD/assets/138754105/4d42cfdc-656a-41fb-983d-86d380a4a54d)

**Comment by gwblok** [comment]
Thanks, I'll try to wrap this in a try / catch.

It would appear that HP doesn't have the 8C26 platform information available, I've reached out to HP to check on that.
But this does raise the point that this alone shouldn't break the GUI, I'll see what I can come up with.

**Comment by gwblok** [comment]
I've added a try catch and some additional logic to the GUI process, hopefully that resolves it.
It will not go live until the next module push, probably after June's Patch Tuesday.

**Comment by gwblok** [comment]
As a note, this is a new HP Model, and HP Hasn't released and updated BIOS yet, which is why that command isn't working.  This was a situation I have never encountered before, so I didn't build in the logic to address it.  Thanks for posting this issue, and hopefully the next release with the changes made will address it.

**Comment by gwblok** [comment]
Closing, please reopen if you continue to have issues
