### ISSUE TITLE
Install all dot net feature updates durring install

### ISSUE THREAD

**Issue by Abe-Telo** [OSDeploy/OSD#142]
**Is your feature request related to a problem? Please describe.**
When installing windows 10 home. Cant activate windows until i update computer.  Once i update computer i can use the troubleshoot to activate windows.  

**Describe the solution you'd like**
Have .net 3.5 or whatever dot net versions windows activation relies on. 
Sometimes i need to use updates multiple times until the correct one is installed. 

**Additional context**
Issue is only in windows 10 Home, 
Tried on surface devices.

**Comment by gwblok** [comment]
I'd recommend scripting this in your own processes.  You can either enable .Net 3.5 while still in WinPE, or leverage a SetupComplete file to enable things and trigger Windows Updates.
