### ISSUE TITLE
WinPE 10.1.26100.1 Error in Deployment phase Export

### ISSUE THREAD

**Issue by sys-adm90** [OSDeploy/OSD#146]
Microsoft has released a new version of the ADK and WINPE images based on Windows 11 24H2.
https://learn.microsoft.com/en-us/windows-hardware/get-started/adk-install#download-the-adk-101261001-may-2024

I have used this to build a new OSDCloud boot image.
The deployment is working fine but in the Export phase i see 2 errors in the logfiles. Get-WindowsCapability and Get-WindowsPackage.
When i replace the PE Image with an older version and rebuild the OSDCloud boot image it's working fine.

I deploy a Windows 11 23H2, it's not a preview release or something. If more logs are needed tell me which one.

=========================================================================
2024-05-29-102100
Export Operating System Information
Export WinPE PowerShell Commands to C:\OSDCloud\Logs\Get-CommandWinPE.txt
Export Appx Provisioned Packages to C:\OSDCloud\Logs\Get-AppxProvisionedPackage.txt
Export Windows Capability to C:\OSDCloud\Logs\Get-WindowsCapability.txt
PS>TerminatingError(Get-WindowsCapability): "The request is not supported.
"
Get-WindowsCapability : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.5.14.1\Public\OSDCloud.ps1:1985 char:23
+ ...   $Report = Get-WindowsCapability -Path C:\ -ErrorAction Ignore | Sel ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
Get-WindowsCapability : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.5.14.1\Public\OSDCloud.ps1:1985 char:23
+ ...   $Report = Get-WindowsCapability -Path C:\ -ErrorAction Ignore | Sel ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand

Export Windows Edition to C:\OSDCloud\Logs\Get-WindowsEdition.txt
Export Windows Optional Features to C:\OSDCloud\Logs\Get-WindowsOptionalFeature.txt
Export Windows Packages to C:\OSDCloud\Logs\Get-WindowsPackage.txt
PS>TerminatingError(Get-WindowsPackage): "The request is not supported.
"
Get-WindowsPackage : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.5.14.1\Public\OSDCloud.ps1:2003 char:23
+ ...    $Report = Get-WindowsPackage -Path C:\ -ErrorAction Ignore | Selec ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsPackageCommand
Get-WindowsPackage : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.5.14.1\Public\OSDCloud.ps1:2003 char:23
+ ...    $Report = Get-WindowsPackage -Path C:\ -ErrorAction Ignore | Selec ...
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsPackage], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsPackageCommand

=========================================================================

**Comment by dany20mh** [comment]
I attached my logs for the similar issue I have too here.

[2024-06-24-075019-Deploy-OSDCloud.log](https://github.com/user-attachments/files/15960488/2024-06-24-075019-Deploy-OSDCloud.log)

**Comment by gwblok** [comment]
I have confirmed the bug in 24H2 ADK.
At this point, other than checking for 24H2 ADK and disabling those things, unsure what else to do. It's not an OSDCloud problem, it's an ADK issue.
I'll keep messing with it, but for now, that seems like the only option, check for ADK version and skip those things

**Comment by gwblok** [comment]
For now, I'm having it check the build of WinPE, if 26100 then it will use the DISM versions of the command instead of PowerShell.  It's not as pretty, but it gets the data.

![image](https://github.com/OSDeploy/OSD/assets/26312309/5da09b96-a187-49cc-b863-5ad5130cfeef)


This won't be live until the module is updated next time.
If you want to test now, just overwrite your OSDCloud.ps1 file in your module with the one from GitHub
