### ISSUE TITLE
case-insensitive  HP DriverPack auto-detection via product

### ISSUE THREAD

**Issue by AlkHacNar** [OSDeploy/OSD#150]
I don't know the exact problem, why OSDCloud auto selct the wrong driver pack, but I think the function selects via product and is not case-sensitive. The product on my notebook is 8ABB and the selected one have 8abb. Correct me if I'm wrong

![shared image (1)](https://github.com/OSDeploy/OSD/assets/78980489/f64540bd-f283-44b9-8a9b-8412ed2c8a33)
![shared image](https://github.com/OSDeploy/OSD/assets/78980489/abb6b91e-1439-4d2e-a324-e3cd30c4d4ef)

**Comment by CCRandyM** [comment]
Hey, yeah we have the same thing with 2 HP models. from the top of my head but will check in next week with screenshots:

HP Elite x360 1040 14 inch G10 2-in-1 Notebook PC
HP EliteBook 860 16 Inch G10 Notebook PC

all detected as the zbook firefly.

**Comment by gwblok** [comment]
Right, they use the same driver pack, the detection is based on the product code. 

![image](https://github.com/OSDeploy/OSD/assets/26312309/b289ccd8-9df3-4bbe-a672-d592cd528e64)
