### ISSUE TITLE
Length Error for HPCMSL

### ISSUE THREAD

**Issue by dany20mh** [OSDeploy/OSD#151]
I have a fresh image built with WinPE 24H2 (10.26100) and it goes fine all the way to the end it throws errors for two things, 

```
HPCMSL in Gallery: 1.7.1 vs Installed: 1.7.1
The property 'Length' cannot be found on this object. Verify that the property exists.
At X:\Program Files\WindowsPowerShell\Modules\HP.ClientManagement\1.7.1\HP.ClientManagement.psm1:1777 char:24
+           for ($i = 0; $i -lt $refined_doc.Length; $i++) {
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
The property 'Length' cannot be found on this object. Verify that the property exists.
At X:\Program Files\WindowsPowerShell\Modules\HP.ClientManagement\1.7.1\HP.ClientManagement.psm1:1777 char:24
+           for ($i = 0; $i -lt $refined_doc.Length; $i++) {
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict
```

In addition, I also get errors for WindowsCapability too. (this might be related to #146) 

```
Export Windows Capability to C:\OSDCloud\Logs\Get-WindowsCapability.txt
PS>TerminatingError(Get-WindowsCapability): "The request is not supported.
"
Get-WindowsCapability : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.6.18.1\Public\OSDCloud.ps1:1985 char:23
+ ...   $Report = Get-WindowsCapability -Path C:\ -ErrorAction Ignore | Sel ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
Get-WindowsCapability : The request is not supported.

At X:\Program Files\WindowsPowerShell\Modules\OSD\24.6.18.1\Public\OSDCloud.ps1:1985 char:23
+ ...   $Report = Get-WindowsCapability -Path C:\ -ErrorAction Ignore | Sel ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-WindowsCapability], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsCapabilityCommand
```

[2024-06-24-075019-Deploy-OSDCloud.log](https://github.com/user-attachments/files/15960486/2024-06-24-075019-Deploy-OSDCloud.log)

**Comment by gwblok** [comment]
Does the HPCMSL error break anything, or just throw an error and continue?

I've been less than impressed with 24H2 ADK.

**Comment by dany20mh** [comment]
So far non of those error break anything (at least it doesn't look like it) and it goes in and finish the process.

P.S. I might be wrong with this portion and I have to test it furhter, but I don't see the computer doing any HPIA (driver, firmware, ...) stuff.

**Comment by dany20mh** [comment]
Actually, I just saw your commit for "Write-CMTraceLog," maybe that's why I thought it was not applying the HPIA; I will try that later. 

Let me know if you need me to test any for HPCMSL length issues.

**Comment by dany20mh** [comment]
@gwblok I just run one test.

I replaced the whole repo (for v24.7.4.1) with what was on the machine during WinPE and I didn't get this error anymore.

Also no error for 146 issue too.

**Comment by gwblok** [comment]
I made a lot of updates last week, been focusing on HP devices, adding the ability to lookup the latest HP driver pack live while in WinPE (using the same process as CMSL does), download and extract the driver pack to c:/drivers so it will get applied while offline

**Comment by gwblok** [comment]
This should be resolved now.
