### ISSUE TITLE
ImageFileUrl error with URL query parameters

### ISSUE THREAD

**Issue by iainbrighton** [OSDeploy/OSD#16]
**Describe the bug**
When downloading an image from a URL using the `ImageFileUrl` parameter, if the URL contains a query string i.e. an Azure file with a SAS token, the `WebFile.ps1` script throws an error. In short, the query parameters are not removed and end up being included in the local destination filename - which is invalid.

**To Reproduce**
Run `Start-OSDCloud -ImageFileUrl "<Any_URL_with_query_parameters>"`

**Expected behavior**
I would expect the URL query parameters to be removed/not included in the local file

I have [fixed the problem in a fork](https://github.com/VirtualEngine/OSD/commit/e67af0e6cb6e3beaa0d826d12f530684af3a9e8b) and I am happy to submit a pull request if the code meets your requirements/expectations.

Thanks,
Iain

**Comment by OSDeploy** [comment]
This looks and worked great.  I added this to the code for the next release (days) and appreciate the effort.  David
