### ISSUE TITLE
HP G11 generation not in CloudDriverPacks

### ISSUE THREAD

**Issue by brasil1983** [OSDeploy/OSD#160]
HP drivers for G11 models are not pulling from the catalog.
Example missing elitebook 640 g11 driver pack
![image](https://github.com/user-attachments/assets/2ecab527-b651-408a-b134-e65532d4faaa)

https://hpia.hpcloud.hp.com/downloads/driverpackcatalog/HP_Driverpack_Matrix_x64.html

**Comment by gwblok** [comment]
NOTE, you can also download that softpaq and extract it to your USBFlash Drive into the correct folder, and it will automatically be DISM'd in offline while in WinPE

That is typically what I do, it is faster.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/32460f24-d8fa-47fd-b259-691e460ae1cc">
