### ISSUE TITLE
Possible to run OSDeploy in WinPE AFTER a custom Image has just been deployed?

### ISSUE THREAD

**Issue by spotopolis** [OSDeploy/OSD#163]
I have been trying to figure this out for a few days now messing with the $global.MyOSDCloud variables and have not been able to come up with a solution (at least on my own). Any help would be greatly appreciated.

I would like to use the driver function of OSDeploy to run after I have already deployed a custom .wim to the drive.

How if at all possible could I call OSDeploy to run but skip everything but the detection of what system I am currently running on so it can download the proper Windows Updates, Windows Drivers, and OEM Device Drivers, and then run them during first boot?

I have tried to set $global.MyOSDCloud variables like I mentioned before, but when I tried skipping the Image sections, the script didnt like that and stopped running.

I have an unattend.xml file I am already using, so I dont want to overwrite that, but if I am able to add a command to run manually that would work.

I would just like to make sure that the different devices I am installing this image to get the drivers and updates they need without having to constantly update the image with new drivers/firmware.

**Comment by AkosBakos** [comment]
I would suggest you to import the OSD PS module and use it in the OOBE phase, with oobe.cmd.

But if you just want to install OS and driver updates, you can use the following two one-liners:
Install-WindowsUpdate -UpdateType Driver -AcceptAll -IgnoreReboot

Install-WindowsUpdate -MicrosoftUpdate -AcceptAll -IgnoreReboot -NotTitle 'Preview'

--> These are in these module: Import-Module PSWindowsUpdate -Force

**Comment by spotopolis** [comment]
I dont see it in the documentation, but does the OOBEDeploy function and install OEM driver and firmware just like OSDCloud will do from inside WindowsPE? Im wanting to get the same function where it will autodectect the device and OS, then download the driver pack and save it to the drive to then install later during the OOBE section.

Thats the function I am looking to use. From what I can see OOBEDeploy will only pull from Windows update, correct?

**Comment by AkosBakos** [comment]
In the OOBE phase yes, you have right.
But in the WinPE phase you can have a look at the[ Invoke-OSDCloudDriverPack](https://github.com/OSDeploy/OSD/blob/master/Public/Functions/DriverPack/Get-MyDriverPack.ps1) function.
