### ISSUE TITLE
Initialize-OSDCloudStartnetUpdate.ps1 error

### ISSUE THREAD

**Issue by chield** [OSDeploy/OSD#165]
**Describe the bug**
In the command screen (after Manufacturer, Model and Serialnumber I receive an error Get-Ciminstance: Provider load failure and will display TPM and Autopilot: Not supported.

After this, the process wil continue without any error. 

**To Reproduce**
Boot from prepped USB drive

**Expected behavior**
In an earlier version never saw this error message.

 - Version: 24.8.5.1

**Comment by gwblok** [comment]
Sorry, where are you getting this error?

Can you provide a screen capture?



<img width="651" alt="image" src="https://github.com/user-attachments/assets/2deadc67-7a09-42c0-9acd-e9d20a47cdca">
<img width="651" alt="image" src="https://github.com/user-attachments/assets/2deadc67-7a09-42c0-9acd-e9d20a47cdca">

**Comment by chield** [comment]
<img width="655" alt="Error OSDCloud" src="https://github.com/user-attachments/assets/5d93e72b-6763-4339-8f98-e4db3f203ad0">

**Comment by gwblok** [comment]
if you open powershell and run the same command, what happens?
Get-CimInstance -Namespace "ROOT\cimv2\Security\MicrosoftTpm" -ClassName Win32_Tpm | Select-Object -Property *

**Comment by chield** [comment]
<img width="838" alt="OSDCloud - error -" src="https://github.com/user-attachments/assets/7d736dc8-e8fe-4943-8626-27f4000a645b">

see here the result

**Comment by AkosBakos** [comment]
Did you enabled the TPM chip?
WinPE error says, that the TPM was not detected any TPM.

**Comment by chield** [comment]
TPM is enabled

**Comment by chield** [comment]
![2024-09-23_11-22-54](https://github.com/user-attachments/assets/af8696cb-3ac0-4a96-bf99-672c33850372)

Error with running Get-TPM from the WinPE.

**Comment by chield** [comment]
Tried to create the OSDCloud configuration on a physical Windows 10 device, created a new USB stick and now the error is gone. My reference machine that I've been using the last months is a Windows 10 VM on Hyper-V, but apparently the OSD proces is not working for 100%. 

Anyhow, it's working now and I can continue with deploying existing devices. Thanks for the support all!!
