### ISSUE TITLE
Use OSDCloud DirverPack with SCCM

### ISSUE THREAD

**Issue by trongtinh1212** [OSDeploy/OSD#166]
Hi there
I just read [this](https://www.osdcloud.com/integration/mdt-use-osdcloud-driverpacks-in-a-task-sequence), this is for MDT, How i can use this driverpack for SCCM Task sequence ?
Thanks

**Comment by trongtinh1212** [comment]
i just read this, i'm not sure 
[Invoke-OSDCloudDriverPackCM](https://github.com/OSDeploy/OSD/blob/master/Docs/Invoke-OSDCloudDriverPackCM.md)
`cmd.exe /c start /wait PowerShell -ExecutionPolicy Bypass -Command Invoke-OSDCloudDriverPackCM`

**Comment by gwblok** [comment]
Are you looking to download the Driver Pack during OSD and apply it?

That function will download the driver pack that it matches to your system to c:\Drivers

From there, you'll need to extract and apply.

Before you try that funciton, you'd have to have all of the pre-reqs in WinPE setup.
A simple way to do that is in a step, run iex (irm sandbox.osdcloud.com), and that will setup your pre-reqs

<img width="622" alt="image" src="https://github.com/user-attachments/assets/189b0b00-0579-40e3-a49b-e6765b563346">

Then you can launch another PowerShell Step that with that Function
Invoke-OSDCloudDriverPackCM

Then do your testing, make sure it downloaded what you wanted to C:\Drivers, then you can extract and apply

**Comment by AkosBakos** [comment]
Any help on that @trongtinh1212?

**Comment by trongtinh1212** [comment]
I guess i have the right answer, thanks @gwblok @AkosBakos , i will close the issue
