### ISSUE TITLE
Old ESD list being used causing Windows 11 to install twice

### ISSUE THREAD

**Issue by Crammy** [OSDeploy/OSD#170]
Hi,

Looking into osdeploy and could see the ESD file being used as the latest OS uses a file from Dec 2023.  I can see the logic here:

https://github.com/OSDeploy/OSD/blob/a51ff73562dad04128cc958c7073b3f7ba21262a/build/Build-OSDCloudOperatingSystemsv3.ps1#L27

The cab files being downloaded and expanded out for use in "Catalogs\CloudOperatingSystems.json".  Is there a new way to find latest ESD files?  Without a code change here osdeploy will be very slow on image deployments and will install a old ESD version and first reboot install the latest build.  I see Gary Town (gwbloke) last made the change moving from WSUS to cab files.

**Comment by AkosBakos** [comment]
Used ESDs are always updating after patch Tuesday. Except now in August (due vacations) and in Sept (due conference reasons).
If you want to patch your system after the installation, use PSWindowsUpdate PowerShellGallery module or install the specified CU like that: https://[gist.githubusercontent.com/AkosBakos/d9d64ee00e401048094fce641fe4355a/raw/CU.ps1](https://gist.githubusercontent.com/AkosBakos/d9d64ee00e401048094fce641fe4355a/raw/CU.ps1)

**Comment by Crammy** [comment]
I think you point of the issue being raised.  The cab file in the code 'products_win11_20231208.cab' (as highlighted in this issue) is an old ESD file information file.  It will be always an old ESD file first used.  On the first reboot of the machine, it will download the latest Windows again.  This leads the Windows being installed twice using the code since Dec 2023.  It's nothing todo when as in your comment.
