### ISSUE TITLE
Error messages when using start-OSDCloud -FindImageFile (24.10.8.1)

### ISSUE THREAD

**Issue by pebernath** [OSDeploy/OSD#179]
When the **Edit-OSDCloudWinPE** set with  **-StartOSDCloud '-FindImageFile'** there are 2 error messages in the WinPE Powershell.

As the WinPE booting up and start running -StartOSDCloud 2 error messages present regarding couldn't found '.esd' and .'*install.swm' files. (Line 17-18)
![error](https://github.com/user-attachments/assets/f1a422be-9ff2-4295-91a5-59b32500aa63)

**Comment by gwblok** [comment]
Confirmed, small tweak to code resolved it in my testing.  Fix is on GitHub, will be incorporated the next module release.
