### ISSUE TITLE
Test-DISMFromOSDCloudUSB always enumerates to True for Lenovo devices

### ISSUE THREAD

**Issue by skyblaster** [OSDeploy/OSD#181]
When testing on a Lenovo and the following folder is present, the Test-DISMFromOSDCloudUSB function enumerates to True, even though a $ComputerProduct sub folder does not exist:
E:\OSDCloud\DriverPacks\DISM\Lenovo\

This is due to `"PackageID":  null,` statements in the [Lenovo DriverPack Catalog](https://github.com/OSDeploy/OSD/blob/master/Catalogs/LenovoDriverPackCatalog.json)

Causing line 30 to fail to complete the path:
https://github.com/OSDeploy/OSD/blob/809ff2d7d9850c18eb9a7170c8e5493a42e70f2a/Public/OSDCloudTS/Test-DISMFromOSDCloudUSB.ps1#L30

And line 41 to return True
https://github.com/OSDeploy/OSD/blob/809ff2d7d9850c18eb9a7170c8e5493a42e70f2a/Public/OSDCloudTS/Test-DISMFromOSDCloudUSB.ps1#L41

**Comment by skyblaster** [comment]
Further testing on a Dell Latitude 5400, the following folder produces a True result:
E:\OSDCloud\DriverPacks\DISM\Dell\08B8\

Whereas the following PackageID folder results in False:
E:\OSDCloud\DriverPacks\DISM\Dell\84RYJ\

I'm not sure how to explain this one at the moment.

**Comment by skyblaster** [comment]
To resolve the PackageID issue for HP and Dell, the following two lines simply need to be reversed:
https://github.com/OSDeploy/OSD/blob/809ff2d7d9850c18eb9a7170c8e5493a42e70f2a/Public/OSDCloudTS/Test-DISMFromOSDCloudUSB.ps1#L24-L25

**Comment by gwblok** [comment]
Thanks @skyblaster, Sorry, been away from my computer for awhile, and still will be barely around for a bit.
Thanks for spotting that issue with lines 24 & 25 switched.  

Is this entire things resolved now, or are you still having some issues?
My test pool of Lenovo devices isn't good.  I have a T480 laptop.

Let me know if you're still having issues and I'll put it on my list to look into. 

Glad someone is using this feature, I've been loving it, but 95% of my testing is on HP devices, and it's been working well.

**Comment by skyblaster** [comment]
Thanks @gwblok. I believe the merge resolves the issue completely, so I'll close the issue now.

I'll do more testing once it's been pushed to the PSGallery. If I happened to break anything I'll open a new issue and hopefully another PR to fix.

**Comment by gwblok** [comment]
@skyblaster , thanks so much for being on top of that and digging through the code.  
With the new baby, and taking care of the other 8 kids, I've been a bit overwhelmed.  This is my first night on my computer in the last week!
