### ISSUE TITLE
Update Lenovo Driver Catalog

### ISSUE THREAD

**Issue by ThiloL** [OSDeploy/OSD#182]
How to update Lenovo driver catalog to add:

`https://download.lenovo.com/pccbbs/mobiles/tp_t14-p14s_gen_4a-t16-p16s_gen_2a_w11_21_22_24_202409.exe`

for T14 Gen 4

**Comment by skyblaster** [comment]
For new and old driver packs alike, I would highly recommend checking out the DISM driver injection method.
1. Download the driver pack of your choice
2. Find the product code of your device on the bottom of the chassis or with the Get-MyComputerProduct function
3. Create a new folder on your OSDCloudUSB partition:
     Example for your T14: D:\OSDCloud\DriverPacks\DISM\Lenovo\21K3 (or 21K4)
4. Extract the driver pack to this new folder
5. Image as usual. I always choose "None" for driver pack when using this method.

Keep in mind that as soon as you create the OSDCloud\DriverPacks\DISM\Lenovo\ folder, you will be subject to issue #181 (until patched), so make sure you create the correct subfolder.
