### ISSUE TITLE
Dell Driver

### ISSUE THREAD

**Issue by T-Doschke** [OSDeploy/OSD#21]
**Describe the bug**
Get-OSDCatalogDellDriverPack.ps1 defines the $DownloadBaseURL as
$DownloadsBaseUrl       = 'http://downloads.dell.com/'

Dell delivers here some Downloads but it seems its a mirror from original source.
So in this mirror is at the moment a broken .CAB file for Dell latitude 7490 (Model 081C)

If i try to Download Driverpack manually i get this page:
https://www.dell.com/support/home/de-de/drivers/DriversDetails?driverId=3F3NX
And that shows that Download base is https://dl.dell.com
$DownloadsBaseUrl       = 'https://dl.dell.com/'

Think its for all other downloads the same base URL https://dl.dell.com

So change this line in Get-OSDCatalogDellDriverPack.ps1

cause script has the MD5 checksum from catalog.xml its possible to test the downloaded .CAB against its MD5 to see it is correct.

If i manually change this line i get the correct .CAB file, but in WinPE Phase OSD will be updated leading to "wrong" base URL and getting the broken .CAB File.

**Comment by gwblok** [comment]
@T-Doschke, can you confirm if this is still an issue?  I'm trying to clean up old open issues.  Thanks

**Comment by T-Doschke** [comment]
Have solved it on my own, by extending procedures to use self managed driverpacks into OSDeploy process if they exist for special devices.


Mit freundlichen Grüßen / Best regards

Thomas Doschke


[cid:TER_Group_Signatur_70x70_4abc6771-99a7-44b6-896b-e6a5f43f172a.png] Thomas Doschke
Head of Infrastructure
TER Chemicals Distribution Group
T       +49 40 300 501 8173<tel:+49%2040%20300%20501%208173>
E       ***@***.******@***.***>

***@***.***>
www.terchemicals.com<https://www.terchemicals.com/en.html>
[cid:linkedin_signatur_27x27_6ef09de8-5262-4b7d-822d-d9c474e190a6.png]<https://www.linkedin.com/company/ter-chemicals-distribution-group>       [cid:facebook_signatur_27x27_e9c9b8d5-a2dd-4d2e-b056-f4ed5a60b253.png] <https://www.facebook.com/TERGROUP>      [cid:x_89304c58-f352-4f84-a630-9ba7f3a624e3.png] <https://twitter.com/TerChemicals>     [cid:xing_signatur_27x27_01f5bf47-e844-4a1d-a2d2-efaab0879087.png] <https://www.xing.com/companies/terhell%26co.gmbh>

        [cid:ecovadisbannerv2_80310cbc-261c-4ecc-af11-ed8ff46b8c83.png]

        TER Chemicals GmbH & Co. KG
Börsenbrücke 2, 20457 Hamburg
Postfach/P.O. Box 113325, 20433 Hamburg
Germany

Commercial Register: HRA 128759 (Hamburg Local Court)
Sales Tax Identification Number: DE 353824235
Personally liable shareholder: TER Chemicals Verwaltungs GmbH, HRB 175509 (Hamburg Local Court)
Headquarters: Hamburg
Managing Directors: Christian Westphal, Andreas Früh, Uta Seiler

General terms of sale can be sent on request or downloaded from our website.<https://www.terchemicals.com/en/quality-support/downloads.html>
Von: gwblok ***@***.***>
Gesendet: Montag, 18. März 2024 17:38
An: OSDeploy/OSD ***@***.***>
Cc: Doschke, Thomas ***@***.***>; Mention ***@***.***>
Betreff: Re: [OSDeploy/OSD] Dell Driver (Issue #21)


Sie erhalten nicht oft eine E-Mail von ***@***.******@***.***>. Erfahren Sie, warum dies wichtig ist<https://aka.ms/LearnAboutSenderIdentification>


@T-Doschke<https://github.com/T-Doschke>, can you confirm if this is still an issue? I'm trying to clean up old open issues. Thanks

**Comment by gwblok** [comment]
Closing Issue.  Thanks @T-Doschke for the quick response.
