### ISSUE TITLE
Windows 10 Pro NL is installing Education N NL version

### ISSUE THREAD

**Issue by hogendoorn** [OSDeploy/OSD#28]
**Describe the bug**
When  i try to instal Windows 10 Pro NL Windows 10 Education N version is actually installed.

**To Reproduce**
See screenshots.

**Expected behavior**
Installing the correct version.

**Screenshots**
![Screenshot_6](https://user-images.githubusercontent.com/12395796/171275036-f7ce2d9c-6e8c-4623-81ef-c8fa7ef287a6.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/12395796/171275059-507b6a5c-2418-4196-a2c4-3d7575b18548.jpg)

**Comment by OSDeploy** [comment]
Is this working?  I didn't make a change ...
