### ISSUE TITLE
MDT OSDCloud Driver Packs for HP not downloading

### ISSUE THREAD

**Issue by NordloRobertNilsson** [OSDeploy/OSD#3]
Hi guys, great job on the Powershell modules! I'm using OSDUpdate a lot in our MDT and are now working on implementing OSDCloud Driver Packs. I have done all the steps in the guide at https://osdcloud.osdeploy.com/concepts/mdt-osdcloud-driverpacks, I have injected the latest OSD module released today and curl (64-bit under C:\Windows\System32 in the Winpe-image (also 64-bit)), updated deploymentshare, replaced boot image in WSD.

The computer are booting (Elitebook 840 G8), applies OS-image, runs Save-ZTIDriverPack (Poweshell and Curl starts), but exits saying the HP is not supported and no driver pack is dowloaded.

After a couple of minutes the computer reboots and doesn't run Expand-ZTIDriverPack since there is no driver packs under C:\Drivers.

I have also tried using OSDCloud.usb and iso with same result.

Also tried an older ProDesk 800 G1 with the same problem.

What am I missing?

Regards

Robert

**Comment by NordloRobertNilsson** [comment]
Update: You can close this "issue". Works like a charm after I updated OSD in the WinPE boot image.

**Comment by OSDeploy** [comment]
Glad it worked out ... yes having to put it in WinPE helps.  Sorry for the delay in responding
