### ISSUE TITLE
Get-OSDCatalogLenovoBios

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#34]
In Get-OSDCatalogLenovoBios.ps1 script, Lenovo is using 'SupportedProduct' XML tag and not 'Product'
--> using -Compatible filter the result is due to this wrong filter, is empty.

Get-OSDCatalogLenovoDriverPack -Compatible is correct.

**Comment by AkosBakos** [comment]
![1](https://user-images.githubusercontent.com/44706641/177183555-acbeb05d-cd30-414c-a67b-745a244003ca.jpg)

**Comment by AkosBakos** [comment]
![2](https://user-images.githubusercontent.com/44706641/177183648-655b79bf-647f-45fd-bb2e-2ff9e6987912.jpg)

**Comment by gwblok** [comment]
@AkosBakos, is this something that still needs to be changed?  Did you resolve the issue?  What's the status on this?

**Comment by AkosBakos** [comment]
@gwblok the new function (Get-LenovoBiosCatalog) seems to work. The old functions which I was referencing back July 2022, doesn't exist anymore.
