### ISSUE TITLE
Update WSUSXML with June CU

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#35]
Autopilot has an Issue with the May cumulative update.
It would be nice, when the base OS would be downloaded and applied inclusive the June CU.

**Comment by OSDeploy** [comment]
"an issue" is incredibly vague. I'm gonna need specifics here

**Comment by AkosBakos** [comment]
Reading hardware hash has an issue:
- https://summalai.com/?p=4179
- https://www.reddit.com/r/Intune/comments/udwyl7/getwindowsautopilotinfo_error/

--> Installing June CU solves this problem

**Comment by agressiv** [comment]
While Microsoft has released updated ISO's including the June updates, they have not released those to WSUS, which (I would assume) is the source of the XML catalogs as part of this module.  Indeed, the May update is most current for Windows 10 and Windows 11 is still stuck back  in November.

If there is a URL to the latest ESD from Windows Update, it's simply not been made accessible to WSUS.

**Comment by OSDeploy** [comment]
> Sure - when it comes directly from MSFT, you cannot do anything. I was just wondered why beginning of July, ESD still comes with May CU.

This is accurate. Akos, the files come from WSUS and they are not released monthly like MSDN or MVLS. I do understand that the May CU introduced the HASH error, but I absolutely tested this May release and it did not have the HASH error. Can you confirm again if the version in OSDCloud has this error?  If so, I will roll back the 21H2 build to the original release (from 2021) and not the May release. There is no option to use any other build so please test (for real) and verify.

**Comment by AkosBakos** [comment]
Guys, thanks anyway for your comments and thoughts. All of you have right.
The issue is a bit direction TPM and/or generell Intel Infineon chip.

On a Dell, Surface, Vmware, the process with May CU works fine.
On a new X1 carbon Lenovo device with this Infineon chipset won't work. Just after installing the July CU.
On an other Lenovo X1 carbon model with chip ST microelectronics works as well.

--> please don't roll back the OSDCloud release

**Comment by mantis** [comment]
I seem to be hitting the TPM issue, however:

```
(Invoke-WebRequest -Uri https://go.microsoft.com/fwlink/?LinkId=841361 -OutFile handle.cab) 
Expand handle.cab -F:products.xml products.xml
[XML]$xmlfile = Get-Content products.xml
$xmlfile.MCT.Catalogs.Catalog.PublishedMedia.Files | select -ExpandProperty childnodes  | where {$_.languageCode -like 'en-GB' -and $_.architecture -eq 'x64'}  | Out-GridView -PassThru
```

That offers:

19044.1288.211006-0501.21h2_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-gb.esd

which is newer then

19044.1706.220505-0136.21h2_release_svc_refresh_CLIENTBUSINESS_VOL_x64FRE_en-gb.esd

Should it not always grab latest release ?

**Comment by OSDeploy** [comment]
> 
I use the Feature Update catalogs from WSUS. These are not the same as the Media Creation Tool XML or the MVLS lists or the MSDN Subscriber Downloads

**Comment by OSDeploy** [comment]
> Guys, thanks anyway for your comments and thoughts. All of you have right. The issue is a bit direction TPM and/or generell Intel Infineon chip.
> 
> On a Dell, Surface, Vmware, the process with May CU works fine. On a new X1 carbon Lenovo device with this Infineon chipset won't work. Just after installing the July CU. On an other Lenovo X1 carbon model with chip ST microelectronics works as well.
> 
> --> please don't roll back the OSDCloud release

21H2 has been rolled back in the lastest OSD module as the June ESD file has other issues

**Comment by AkosBakos** [comment]
As workaround for these devices, you can use iex (irm cu.osdcloud.ch) before "wpeutil reboot". It installs the August CU for W10 21H2.

**Comment by OSDeploy** [comment]
The 12H2 image was reverted back to the original release as we discovered other issues.  Please verify and thanks!

**Comment by AkosBakos** [comment]
21H2 still comes with May CU.
22H2 has already included the Sept CU.
![3](https://user-images.githubusercontent.com/44706641/197141348-fd7637a9-62fd-489e-807b-440c2c2e948f.jpg)
![1](https://user-images.githubusercontent.com/44706641/197141397-9318fbc7-d68e-473e-9f6f-2e00c1d16b95.jpg)
![2](https://user-images.githubusercontent.com/44706641/197141521-44695145-69dd-4466-a5b2-269215d7c7c9.jpg)

As a workaround for some customers, I am passing the August CU as a PPKG.

**Comment by AkosBakos** [comment]
@gwblok yes it is - but we have found a workaround.
I mean either use the workaround (iex (irm cu.osdcloud.ch) or install directly W11 ;-)
