### ISSUE TITLE
"en-uk" OS language would be awesome

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#37]
It's a simple feature request.
One of my customer would need this OS default language.

**Comment by mantis** [comment]
wouldn't that be en-GB?

**Comment by AkosBakos** [comment]
@mantis you are right. I was a bit confused between Get-WinuserLanguageList and Get-WinSystemLocale.

**Comment by AkosBakos** [comment]
kudos for @mantis
