### ISSUE TITLE
New-OSDCloudUSB throwing an error on GPT disk

### ISSUE THREAD

**Issue by andrewtchilds** [OSDeploy/OSD#42]
Getting error "New-Partition : A parameter is not valid for this type of partition. The parameters MbrType and IsActive cannot be used on a GPT disk." when running `New-OSDCloudUSB` and selecting a GPT partitioned USB drive.

It seems `Clear-Disk` doesn't "clear" the partition type as seen by `Get-Disk`.

![image](https://user-images.githubusercontent.com/17715542/195639730-7b65587e-f5df-4d06-aca3-aabc622187f4.png)

To get around this, I first ran `Get-Disk -Number 1 | Set-Disk -PartitionStyle MBR`, then kicked off `New-OSDCloudUSB` again and it completed successfully.

**Comment by OSDeploy** [comment]
Thanks for adding the fix.  This will be published in the next release
