### ISSUE TITLE
Lenovo L14 / L15 Gen2 W11 driverpack missing in driverpacks.json

### ISSUE THREAD

**Issue by SasStu** [OSDeploy/OSD#48]
We created a OSDCloud Boot Image for one of our customers with a large fleet of Lenovo L14 / L15 Gen 2 (20X1) devices. Deploying Windows 11 22H2 with OSDCloud works like a charm but the devices will start OOBE without a Wifi Adapter.

It seems that the root cause of this is that there is only the W10 driver pack available in OSDCloud for these devices and not the W11 driver pack which exists as well.

 https://support.lenovo.com/us/en/downloads/ds547825-sccm-package-for-windows-10-version-1903-1909-2004-thinkpad-l14-gen-2-l15-gen-2

https://download.lenovo.com/pccbbs/mobiles/tp_l1415gen2_mt20x1-20x2-20x3-20x4_w11_21_202112.exe

Please add the W11 driverpack to the driverpacks.json for those devices.

**Comment by OSDeploy** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/12970006/200918456-cd3fc326-89ea-44e2-a206-a7c193ffe0d9.png)

**Comment by SasStu** [comment]
Great thank you!

**Comment by OSDeploy** [comment]
Ok, this should work quite well in the GUI, but it's the auto-selection that I need to work on, so give that some time to sort out

**Comment by OSDeploy** [comment]
![image](https://user-images.githubusercontent.com/12970006/200919383-ba7023b2-60fd-4c53-b5a6-2b11238b0072.png)

**Comment by SasStu** [comment]
We are currently using OSDCloudGUI so that's fine for us! Thank you for that quick response and fix
