### ISSUE TITLE
Diskpart Logs

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#49]
Would it be possible to forward the *disc* function logs into a log file?
The transcript file starts after the diskpart section.

Before partitioning, like into the $env:TEMP folder would be great for troubleshooting:
https://www.osdcloud.com/azure/technical/log-files

**Comment by gwblok** [comment]
Hey @AkosBakos, what are you looking for?  
OSDCloud isn't using DiskPart by default.  
Are you looking to just have a function dump the disk 0  (Get-Volume) output to a log before & after OSDCloud wipes and formats the drive?

**Comment by AkosBakos** [comment]
I was just looking for some information about the disk partitions, like what about the recovery partition.
I think (Get-OSDGather -Full).DiskPartition could give some useful information.

**Comment by OSDeploy** [comment]
Of the thousands and thousands of times OSDCloud has been run, I don't think there's been much ask for this or much need for troubleshooting disk.  While the detail would be nice to log, is the need for this real or synthetic?  So I tagged this as an Enhancement and assigned it to you @AkosBakos

**Comment by gwblok** [comment]
@AkosBakos 
I'm working on adding that information when OSDCloud is run with: $Global:OSDCloud.DebugMode -eq $true

I can see how it would be helpful during debugging, but not during each run.
I was already adding some other things for debugging, to help with another issue, so I added this in.

Before & After the format, the Partition information is captured into variables, later on, those get written to a log file.

Testing now.

**Comment by OSDeploy** [comment]
There's an OSD Function for that
![image](https://github.com/OSDeploy/OSD/assets/12970006/dad8ccbe-c265-4524-b867-e88c95c5eb5c)

**Comment by AkosBakos** [comment]
Great stuff.
I was just looking for this info, when the clients were having installed with OSDCloud.

I will build in into my OSDCloud OSDGather script and will send to the log files if later on someone needs it.
