### ISSUE TITLE
Image for Dism /online /Cleanup-Image /RestoreHealth

### ISSUE THREAD

**Issue by pgardy** [OSDeploy/OSD#50]
Hi . Thanks for the great project.

I wonder about adding functionality, which would allow to download iso/files of the system, with same os version. architecture, language etc., to be used to repair components corruption.
Quite often a existing system has problems with getting proper files from Windows Update and mounting iso is the only option.
So, to save bandwidth/cost I'm thinking about downloading a full Windows image locally and using it to repair the system.

Sample, usage scenario:
1) import OSD module
2) download and prepare files to mount wim/iso matching the local system
3) try to repair the system with dism. 

(https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/repair-a-windows-image)

**Comment by gwblok** [comment]
You could probably write your own script stealing a lot of the code in the Invoke-OSDCloudIPU function.
That function will detect what is currently running on the device, and also builds the install media from the ESD file.

I've so rarely found /RestoreHealth to actually do anything useful.

If others would find this functionality useful, go ahead and reopen with additional business justifications. 
Thanks
