### ISSUE TITLE
OSDCloud does not automatically reboot when finished

### ISSUE THREAD

**Issue by christiandekker** [OSDeploy/OSD#54]
**Describe the bug**
OSDCloud does not automatically reboot when finished. Option 'restart computer after WinPE' is selected under Deployment Options in OSDCloudGUI. After OS Deployment, just the two minimized screens (one CMD, one PowerShell) are visible. Close these screens will  initiate a reboot.

**To Reproduce**
Perform OS Deployment using OSDCloudGUI

**Expected behavior**
Automatic reboot after OS Deployment

**Screenshots**
N/A

**Additional context**
OSD Module version: 23.3.17.1

**Comment by EskimoRuler** [comment]
Just noticed this as well, the $Global:InvokeOSDCloud variable 'Restart' changed to 'restartComputer' in the MainWindow.ps1 file.

But in the OSDCloud.ps1 file, it is still referencing the name 'Restart', so the default '$false' value is passed.

Looks like the change was made in the 23.2.28.1 release.

**Comment by OSDeploy** [comment]
I'm aware and have the issue fixed. Just waiting on me to push the update in the next day

**Comment by OSDeploy** [comment]
This has been resolved in released OSD 23.3.29.1
