### ISSUE TITLE
Update-OSDCloudUSB -OS not updated for new location of OS images

### ISSUE THREAD

**Issue by christiandekker** [OSDeploy/OSD#55]
**Describe the bug**
Update-OSDCloudUSB -OS still saves OS images to the root of the [OSDCloudWorkspaceDir]\OS folder, while the latest version of OSDCloud seems to use a different format:  [OSDCloudWorkspaceDir]\OS\[BUILDNUMBER] [RELEASE]

**To Reproduce**
1. Deploy an OS using OSDCloudGUI with a fresh OSDCloud USB that does not contain a preloaded OS image
2. The OS that is downloaded during deployment is saved to [OSDCloudWorkspaceDir]\OS\[BUILDNUMBER] [RELEASE] folder
3. Update a fresh OSDCloud USB using Update-OSDCloudUSB -OS
4. The OS that is downloaded is saved to [OSDCloudWorkspaceDir]\OS folder

**Expected behavior**
Both methods should use the same logic for storing OS images

**Additional context**
OSD Module version: 23.3.17.1

**Comment by OSDeploy** [comment]
This will be resolved in the next update

**Comment by OSDeploy** [comment]
This has been resolved in released OSD 23.3.29.1
