### ISSUE TITLE
Anyone Using LTSC images with OSDeploy

### ISSUE THREAD

**Issue by rtruss** [OSDeploy/OSD#57]
I am working on getting my team off of SCCM based OSD and for normal use cases (knowledge workers) the tool is perfect!  Now I need to be able to have my team build ltsc based units and I want the process to be consistent but last time I tried the embed the iso/wim file it would fail as it could not locate the sku online for the get-featureupdate part of the process.  Is there a way to skip that part when selecting a custom 'image'?

Thanks in advance all.

**Comment by OSDeploy** [comment]
If you haven't used it in some time, I'd suggest trying again as Get-FeatureUpdate is not being used any longer. Let me know if you are experiencing a specific error

**Comment by gwblok** [comment]
@rtruss, is this still an issue for you?  If it is, please provide more details on what you're doing so I can wrap my head around what is going on to try to look into it for you.

**Comment by rtruss** [comment]
> @rtruss, is this still an issue for you? If it is, please provide more details on what you're doing so I can wrap my head around what is going on to try to look into it for you.

OMG!  SOOO Sorry.  It's been working now for a while.  Sorry I did not reply earlier.
