### ISSUE TITLE
New-OSDCloudUSB error when starting with a drive previously formatted with GPT

### ISSUE THREAD

**Issue by skyblaster** [OSDeploy/OSD#58]
**Describe the bug**
Unable to run the New-OSDCloudUSB command without first re-formatting the flash drive with an MBR partition layout.

**To Reproduce**
1. Start with a USB flash drive with GPT formatting
2. Run New-OSDCloudUSB
3. Select inserted USB drive

**Screenshots**
![image](https://user-images.githubusercontent.com/1776037/228991848-145c5c8a-7960-4d34-946b-658bf8767671.png)

**Comment by OSDeploy** [comment]
I'm aware of this issue.  It also happens with Rufus formatted drives.  I don't have an ETA on when I can look into this as it probably doesn't happen that frequently.  I can probably Throw a Warning that the drive has to be cleaned manually

**Comment by skyblaster** [comment]
I can make things work by using Get-Disk instead of Get-Disk.osd

```powershell
    $GetUSBDisk = Get-Disk -Number $SelectDisk.Number
    if ($GetUSBDisk.PartitionStyle -eq 'GPT') {
        Write-Verbose '$GetUSBDisk | Set-Disk -PartitionStyle MBR'
        $GetUSBDisk | Set-Disk -PartitionStyle MBR -ErrorAction Stop
```

**Comment by OSDeploy** [comment]
Thanks for sharing.  I'll review, but I don't have an ETA when I can look into this at this time.

**Comment by OSDeploy** [comment]
This issue has been resolved in the latest OSD OSDCloud release
