### ISSUE TITLE
Realtek 8822CE Wireless in WinRE

### ISSUE THREAD

**Issue by skyblaster** [OSDeploy/OSD#62]
**Describe the bug**
If I attempt to integrate Realtek 8822 Wi-Fi drivers into my WinRE using the `-DriverHWID 'VEN_10EC&DEV_C822'` option, Realtek HD Audio drivers are integrated instead.

**To Reproduce**
```powershell
Edit-OSDCloudWinPE -CloudDriver Dell,IntelNet,USB,WiFi -DriverHWID 'VEN_10EC&DEV_C822' -StartOSDGUI
2023-04-06-140412 Mounting C:\OSDCloud\Media\Sources\boot.wim

VEN_10EC&DEV_C822 Realtek Semiconductor Corp. - MEDIA - 6.0.9475.1
UpdateID: 0772e9d4-8051-44a5-840f-18b980630bc5
Size: 11.3 MB Last Updated 01/30/2023 14:04:27
Downloading and expanding to C:\Users\redact\AppData\Local\Temp\1054122884\0772e9d4-8051-44a5-840f-18b980630bc5
https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2023/03/79771bce-481c-4026-9d34-034f3f8d308b_7c71e197f261421dcf0e53b6b0050158672945c5.cab
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.2M  100 11.2M    0     0  5311k      0  0:00:02  0:00:02 --:--:-- 5315k
VERBOSE: Target Image Version 10.0.19041.1
VERBOSE: Successfully added driver C:\Users\redact\AppData\Local\Temp\1054122884\0772e9d4-8051-44a5-840f-18b980630bc5\HDXACPClevo.inf
VERBOSE: Successfully added driver C:\Users\redact\AppData\Local\Temp\1054122884\0772e9d4-8051-44a5-840f-18b980630bc5\HDXClevo.inf
VERBOSE: Successfully added driver C:\Users\redact\AppData\Local\Temp\1054122884\0772e9d4-8051-44a5-840f-18b980630bc5\HDXSSTClevo.inf
VERBOSE: Successfully added driver C:\Users\redact\AppData\Local\Temp\1054122884\0772e9d4-8051-44a5-840f-18b980630bc5\HDXWHITE.inf
```

**Expected behavior**
Download and integrate the following CAB:
[Realtek Semiconductor Corp. - Net - 2024.10.138.0](https://www.catalog.update.microsoft.com/ScopedViewInline.aspx?updateid=6d1e3347-cc0c-4d12-b6c6-0fb4db534c60)
```powershell
https://catalog.s.download.windowsupdate.com/c/msdownload/update/driver/drvs/2022/08/0270b436-5cac-4a52-aa88-e8e1fb7a999d_a5b613e26699adc437dca952f733dbcf5f184dee.cab
```

**Additional context**
Grepping the OSD source, it appeared that this driver may be included in the HPSystemCatalog, however, after adding HP to the -CloudDriver string, WinPE still is not detecting this chipset.

I also attempted to load the driver manually, but can't seem to get around the Read-Only folder attributes within the mounted WIM `C:\Users\redact\AppData\Local\Temp\Mount921933256\Windows\System32\DriverStore\FileRepository`

**Comment by skyblaster** [comment]
> Aare you sure you are manually adding the driver correctly?

I simply mount the WIM using the following command.
```powershell
Mount-OSDWindowsImage C:\OSDCloud\Media\sources\boot.wim
```
I'm sure I'm doing the next part incorrectly, but I extract the contents of the cab using 7-Zip and then attempt to copy the folder to C:\Users\redact\AppData\Local\Temp\Mount921933256\Windows\System32\DriverStore\FileRepository\

I can copy to C:\Users\redact\AppData\Local\Temp\Mount921933256 just fine, but the Windows folder and all sub folders have the Read-Only attribute set.

**Comment by OSDeploy** [comment]
Yes, you are adding drivers to a mounted WIM incorrectly.  If you do it right, you will not get an error.

I've made it easy for you, try this:
![image](https://user-images.githubusercontent.com/12970006/231254612-bdeb37d7-3113-4a09-9073-baf153208756.png)

**Comment by skyblaster** [comment]
Working beautifully now. Thanks for the guidance!
Sorry I missed the -DriverPath option.
