### ISSUE TITLE
Get-FeatureUpdate broken for me since 23.4.25.1 Release

### ISSUE THREAD

**Issue by mmeierm** [OSDeploy/OSD#64]
**Describe the bug**
Since the 23.4.25.1 Release, the Get-FeatureUpdate seems to be broken for me

**To Reproduce**
Get-FeatureUpdate -OSName 'Windows 11 22H2 x64'
gives out Windows 10 22H2 x86

**Expected behavior**
It should give out 'Windows 11 22H2 x64'

**Screenshots**
Not working:
![image](https://user-images.githubusercontent.com/83367358/234598429-d0af9571-30b3-4a19-8c22-0f279eced84a.png)
with an older version:
![image](https://user-images.githubusercontent.com/83367358/234599884-f048958f-c55b-4814-a44e-b943e694f06e.png)

Thanks a lot

**Comment by OSDeploy** [comment]
Thanks for catching this, it's been corrected 
<img width="492" alt="image" src="https://user-images.githubusercontent.com/12970006/234615277-27e928e7-9bcb-4178-99fa-a5c08ae53141.png">

**Comment by mmeierm** [comment]
Thanks a lot, now it's returning x64, but still Windows 10 instead of Windows 11:

![image](https://user-images.githubusercontent.com/83367358/234617861-d695f4b7-59eb-445e-b48e-92bef0fbb5f7.png)
![image](https://user-images.githubusercontent.com/83367358/234618651-a8a98227-47d3-43f9-bcdb-0e0cf5658c73.png)

It seems to me like it ignores the OSName Input?

**Comment by OSDeploy** [comment]
I should have had more coffee today.  I pushed 23.4.26.2 to resolve this issue

**Comment by mmeierm** [comment]
Thank you so much, now it's working just fine.

**Comment by OSDeploy** [comment]
If you don't mind me asking, what do you use this function for?  This was used in OSDCloud, but I've been migrating towards this function instead Get-OSDCloudOperatingSystems 
![image](https://user-images.githubusercontent.com/12970006/234636029-7748acec-19eb-4a4b-be4b-e85026bf942b.png)

**Comment by mmeierm** [comment]
I'm using a custom launcher UI, that enables me to allow our users to upload the devices to Autopilot like i described here: 
https://mikemdm.de/2023/01/29/can-you-create-a-autopilot-hash-from-winpe-yes/
https://mikemdm.de/2023/02/12/automate-autopilot-uploads-with-azure-automation-runbooks/
This Custom UI will automatically detect if Windows 10 or 11 should be installed, based on HW Infos like used CPU, as we only allow Win 10 for older devices, but we still wanted the option to select Language and used DriverPack
![image](https://user-images.githubusercontent.com/83367358/234645914-13c478e1-8408-479a-9142-657acb1c5787.png)
The UI will internally then create the StartOSDCloudGUI Variable with the values and hand over to Start-OSDCloud, which still uses this function...
![image](https://user-images.githubusercontent.com/83367358/234645448-e8c17ea7-bef1-44aa-888e-eaef7e46c79c.png)

**Comment by OSDeploy** [comment]
That looks awesome.  We need to chat about some of the new changes that may be helpful to you!
