### ISSUE TITLE
Get-DellWinPEDriverPack" does not get the latest Dell WinPE10 Driverpack

### ISSUE THREAD

**Issue by Borcon** [OSDeploy/OSD#66]
The function "Get-DellWinPEDriverPack" does not get the latest Dell WinPE10 Driverpack.

There are two issues

Get-DellWinPEDriverPack.ps1 --> Line 33 has the issue.
$null = Invoke-WebRequest -Uri $CurrentDriverPackPage -Method Head -UseBasicParsing -ErrorAction Stop
The method "Head" does not work with the redirect on the Dell website. Replace "Head" with "Get" and the web request is working.

Line 35: $CurrentDriverPack = (Invoke-WebRequest -Uri $CurrentDriverPackPage -UseBasicParsing -Method Get).Links | Where-Object {$_.outerHTML -match 'Download Now'} | Select-Object -ExpandProperty href
"Only Windows with language en-us does find the cab file, because Dell does a redirect depending on the language of your system.
For example a Windows with german language pack does not get the string "Download Now". German windows does get "Jetzt herunterladen". I would recommend to change the line with the following code
$CurrentDriverPack = (Invoke-WebRequest -Uri $CurrentDriverPackPage -UseBasicParsing -Method Get).Links | Where-Object {$_.href -match '.CAB'} | Select-Object -ExpandProperty href

I think searching for "CAB" is the better decision, as it is language independent and i would replace the $.outerHTML with $.href

One important information.
Since this month Dell offers not only WinPE10 drivers, but also WinPE11 drivers.
Maybe this script should be updated to return both URL's or an extra function for WinPE11 drivers.

**Comment by OSDeploy** [comment]
I'll look into this and thanks for letting me know they have a Windows 11 DriverPack now.

**Comment by OSDeploy** [comment]
OSD 23.5.16.2 adds a new function Get-DellWinPE10DriverPack.  Let me know if both of these functions work properly.  If troubleshooting, use the -Verbose parameter

![image](https://github.com/OSDeploy/OSD/assets/12970006/0a1d3a59-355b-4c25-8bf1-02c8762be00b)

**Comment by OSDeploy** [comment]
Closing this issue as completed.
