### ISSUE TITLE
Get-WindowsImage : Reached the end of the file

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#72]
Has anybody issue at the beginning of the Start-OSDCloud script?

![1](https://github.com/OSDeploy/OSD/assets/44706641/fe830fb9-3951-462a-83b4-e7244b879b9c)

![2](https://github.com/OSDeploy/OSD/assets/44706641/63c080c9-e5e6-4f26-931b-a73fcabb3822)

The same script is just working fine on a different ESX host/environment. And I don't think it's a VMware issue... ;-)
Using thick provisioning and UEFI boot in both cases.

**Comment by AkosBakos** [comment]
It was a firewall IPS issue.

**Comment by AkosBakos** [comment]
-

**Comment by AkosBakos** [comment]
It was a firewall IPS issue.

**Comment by nkh1105** [comment]
AkosBakos, what did you do in order to fix this issue?  Seems I am having a similar issue as well.

**Comment by AkosBakos** [comment]
Talked to my best buddy, aka. network engineer and kindly asked for turning off the SSL inspection for the MSFT URLs.

**Comment by nkh1105** [comment]
Thank you AkosBakos!  It is surely something in the network, as off network works just fine.  That gives me something to look into.  I appreciate it.
