### ISSUE TITLE
"There is not enough space..." Install Module call

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#73]
If I start the OSDCloud with this call:
Install-Module OSD -Force

Having this error message:
<img width="1009" alt="1" src="https://github.com/OSDeploy/OSD/assets/44706641/a679369f-1300-4703-9f90-71d4a9078903">

At the end of the WinPE are coming these warning:
<img width="1024" alt="2" src="https://github.com/OSDeploy/OSD/assets/44706641/d53f8f48-ffed-40f0-acbe-bea6257b3b86">

This VM has 40GB SSD + 8GB RAM.

**Comment by mmeierm** [comment]
Same issue here on Hyper-V and also on a Lenovo ThinkPad T590 (1TB SSD and 16 GB RAM). It looks to me like the WinPE Ramdisk (X:\) gets filled up to much during the "Savig PowerShell Modules" part:

before and after this step, I have around 300mb free:
![grafik](https://github.com/OSDeploy/OSD/assets/83367358/a0351d60-9baa-4d59-9733-f930537f3d49)


during less than 50mb from what i see:
![grafik](https://github.com/OSDeploy/OSD/assets/83367358/d33ed5b4-a83d-4f45-a954-69aed222e42f)

**Comment by AkosBakos** [comment]
Great input @mmeierm and very useful screenshots

**Comment by mmeierm** [comment]
From what I can see, the Install-Module OSD -Force cmdlet seems to download the nupkg File to X:\Windows\Temp (~88MB) and then extract it to a random named folder with around 166MB before it failed as the RAMDisk is full, so far not unexpected.

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/172684d9-8b16-4f23-8ae1-d39148fd3155)

It looks to me like the current version contians a pretty large ".git" Folder, that makes the whole package nearly double the size as older ones

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/cf605192-fd09-4fcb-807e-724c4e760bbc)

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/f8604707-846e-4997-99a5-4307ddc6dc35)

**Comment by OSDeploy** [comment]
You guys rock.  I'm not sure what the problem is as my publish script hasn't changed, but things should be working now.
Thanks Akos for pinging me about the issue

![image](https://github.com/OSDeploy/OSD/assets/12970006/a48514d5-158a-41bf-baf3-df876ff32c8f)

**Comment by AkosBakos** [comment]
No more issue on my site:
![1](https://github.com/OSDeploy/OSD/assets/44706641/2a6b0be5-f3cb-42fa-a88a-6c96384c782f)

![2](https://github.com/OSDeploy/OSD/assets/44706641/6c76d5f3-073c-4156-9b7d-9201afde926c)

@mmeierm how does it look on your site?

**Comment by mmeierm** [comment]
Works like a charm :)

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/dacc3657-8f01-4b61-8e6e-0363ae4fe799)

Thank you so much for the quick fix and this wonderful project

**Comment by AkosBakos** [comment]
Issue fix by @OSDeploy - many thanks
