### ISSUE TITLE
Update Microsoft Surface driver catalog

### ISSUE THREAD

**Issue by everydayintech** [OSDeploy/OSD#74]
**Describe the bug**
Microsoft released new surface drivers and pulled old downloads a few days ago. This leads to Surface driver downloads not working correctly.
Could you update the catalog for OSDCloud please?

**Example:**
PackageID 104680 was updated, the old download url is not reachable anymore:

```json
{
        "CatalogVersion":  "23.07.16",
        "Status":  null,
        "Component":  "DriverPack",
        "ReleaseDate":  "23.05.15",
        "Manufacturer":  "Microsoft",
        "Model":  "Surface Pro 9",
        "Product":  "Surface_Pro_9_for_Business_2038",
        "Name":  "Microsoft Surface Pro 9 Commercial Win11 22H2",
        "PackageID":  "104680",
        "FileName":  "SurfacePro9_Win11_22621_23.044.40352.0.msi",
        "Url":  "https://download.microsoft.com/download/e/9/a/e9a35d1b-7b4c-48d4-8619-5301d4c09f65/SurfacePro9_Win11_22621_23.044.40352.0.msi",
        "DownloadCenter":  "https://www.microsoft.com/en-us/download/details.aspx?id=104680",
        "OSVersion":  "Windows 11 x64",
        "OSReleaseId":  "22H2",
        "OSBuild":  "22621",
        "HashMD5":  "36824C20EECF29A3A9A67C2EC6B6BC"
}
```
[https://github.com/OSDeploy/OSD/blob/master/Catalogs/MicrosoftDriverPackCatalog.json](https://github.com/OSDeploy/OSD/blob/master/Catalogs/MicrosoftDriverPackCatalog.json)

**Comment by everydayintech** [comment]
Version 23.7.25.1 fixed the described issue.

**Comment by everydayintech** [comment]
Microsoft released new surface drivers on August 15th and pulled old downloads. Catalog needs to be refreshed again

**Comment by OSDeploy** [comment]
Which model are you trying to deploy?

**Comment by everydayintech** [comment]
Surface_Pro_8_for_Business_with_LTE_Advanced_1982

**Comment by everydayintech** [comment]
Resolved with OSD Version 23.8.18.1

**Comment by AkosBakos** [comment]
=========================================================================
2023-08-25-164325
Microsoft Update Catalog Firmware
PS>TerminatingError(Invoke-WebRequest): "The remote name could not be resolved: 'www.catalog.update.microsoft.com'"
Invoke-WebRequest : The remote name could not be resolved: 'www.catalog.update.microsoft.com'
At X:\Program Files\WindowsPowerShell\Modules\OSD\23.8.18.1\Public\OSDCloudTS\Test-MicrosoftUpdateCatalog.ps1:5 char:20
+ ... atusCode = (Invoke-WebRequest -uri 'https://www.catalog.update.micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], 
WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

LogPath : X:\windows\Logs\DISM\dism.log

Invoke-WebRequest : The remote name could not be resolved: 'www.catalog.update.microsoft.com'
At X:\Program Files\WindowsPowerShell\Modules\OSD\23.8.18.1\Public\OSDCloudTS\Test-MicrosoftUpdateCatalog.ps1:5 char:20
+ ... atusCode = (Invoke-WebRequest -uri 'https://www.catalog.update.micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

WARNING: Unable to download or find firware for his Device
=========================================================================
2023-08-25-164325
Microsoft Update Catalog Drivers
PS>TerminatingError(Invoke-WebRequest): "The remote name could not be resolved: 'www.catalog.update.microsoft.com'"
Invoke-WebRequest : The remote name could not be resolved: 'www.catalog.update.microsoft.com'
At X:\Program Files\WindowsPowerShell\Modules\OSD\23.8.18.1\Public\OSDCloudTS\Test-MicrosoftUpdateCatalog.ps1:5 char:20
+ ... atusCode = (Invoke-WebRequest -uri 'https://www.catalog.update.micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], 
WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
Invoke-WebRequest : The remote name could not be resolved: 'www.catalog.update.microsoft.com'
At X:\Program Files\WindowsPowerShell\Modules\OSD\23.8.18.1\Public\OSDCloudTS\Test-MicrosoftUpdateCatalog.ps1:5 char:20
+ ... atusCode = (Invoke-WebRequest -uri 'https://www.catalog.update.micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

=========================================================================

**Comment by everydayintech** [comment]
![image](https://github.com/OSDeploy/OSD/assets/107258054/4c67f2ba-4795-41a0-a0f8-e0cd31416bd0)

**Comment by AkosBakos** [comment]
A bit interesting thing, the same OSDStart script was working two days before perfectly.

**Comment by AkosBakos** [comment]
(Somehow) since today, it works again.
@everydayintech please close this issue.
