### ISSUE TITLE
Get Windows product by emeded OEM Key

### ISSUE THREAD

**Issue by Abe-Telo** [OSDeploy/OSD#84]
**Describe the solution you'd like** 
It would be cool to get the Windows type based on the Embedded Windows Key from the bios. 
Such as Windows 10 Home, Pro, Enterprise, etc. It would be even cooler If the tool could tell us if the Product key can be used for Win 10 and Win 11.  

I was thinking of even a step forward and filtering the Windows selection from the OSDCloudGUI Menu based on the product key. 

**What this resolves** 
Sometimes I have Windows 10 Pro, But I install Home. 
Sometimes I want to downgrade from Windows 11 to 10, And not sure if the product key allows it. 

Having something like this implemented can save alot of time.

**Comment by AkosBakos** [comment]
I think it could be hard to automate, because the use case is for every user/customer different.
--> if you need this activation, you can simply extend your code with these lines:
https://github.com/AkosBakos/OSDCloud/blob/main/Install-EmbeddedProductKey.ps1

**Comment by Abe-Telo** [comment]
Thank you, i will test it, I assume we use it by adding a line

`Invoke-Expression (Invoke-WebRequest -Uri "https://github.com/AkosBakos/OSDCloud/blob/main/Install-EmbeddedProductKey.ps1" -UseBasicParsing).Content`

Correct?

**Comment by AkosBakos** [comment]
Or simply like that:
Start-Process PowerShell -ArgumentList "-NoL -C Invoke-WebPSScript "https://github.com/AkosBakos/OSDCloud/blob/main/Install-EmbeddedProductKey.ps1" -Wait

**Comment by Abe-Telo** [comment]
> Or simply like that:
> Start-Process PowerShell -ArgumentList "-NoL -C Invoke-WebPSScript "https://github.com/AkosBakos/OSDCloud/blob/main/Install-EmbeddedProductKey.ps1" -Wait
> 

I can confirm it works in windows, but doesn't seem to work in WinPE. Normal behavior? 

In windows I ran the 1.cmd in system32 from his script  and it worked.

**Comment by AkosBakos** [comment]
Check the log file: $env:ProgramData\Microsoft\IntuneManagementExtension\Logs\OSD\Install-EmbeddedProductKey.log
--> if the device has a HW license, it doesn't matter in which phase is getting executed.

**Comment by gwblok** [comment]
The OSD Module has functions for getting the embedded code: https://github.com/OSDeploy/OSD/blob/master/Public/OSDCloudTS/Set-WindowsOEMActivation.ps1

![image](https://github.com/OSDeploy/OSD/assets/26312309/0cc74f7b-a995-42a5-9706-2bde7234b349)

It has worked pretty well for me in my process, applying the Key from older devices and activating Windows 11, but sadly I've had poor luck lately: https://www.zdnet.com/article/can-you-still-get-a-windows-10-upgrade-for-free/

Still works find on newer hardware.

If you OEMActivation = $true in your OSDCloud variables, it should automatically try to get the key and apply it for you.
See my OSDCloud script example:  https://github.com/gwblok/garytown/blob/master/Dev/CloudScripts/win11.ps1

**Comment by gwblok** [comment]
> **Describe the solution you'd like** It would be cool to get the Windows type based on the Embedded Windows Key from the bios. Such as Windows 10 Home, Pro, Enterprise, etc. It would be even cooler If the tool could tell us if the Product key can be used for Win 10 and Win 11.
> 
> I was thinking of even a step forward and filtering the Windows selection from the OSDCloudGUI Menu based on the product key.
> 
> **What this resolves** Sometimes I have Windows 10 Pro, But I install Home. Sometimes I want to downgrade from Windows 11 to 10, And not sure if the product key allows it.
> 
> Having something like this implemented can save alot of time.

I just looked back at the original request, which is different then what I was thinking.
While it's a cool idea, I don't know of a way to do a look up on the OEM code and get the OS it is for.  If you know of a way to do this, let me know and I can see if I can work it into the process.

Today, the best way to do this would be to write a custom script to kick off OSDCloud, have it check for a list of models you image that are known to be Pro, and then have do something like
if (Activation -eq "Pro"){$Activation = "Pro"}
Else {$Activation = "Home"}
Then feed that into your Start-OSDCloud Command line.

Considering this Issue closed unless someone provides a method to do a lookup on the MS Activation Code in the Firmware.

**Comment by skyblaster** [comment]
> While it's a cool idea, I don't know of a way to do a look up on the OEM code and get the OS it is for.

@gwblok, I think you work with a fellow who can give a definitive answer on whether this can be done or not :wink:
He's written several posts on the oa3tool, AP hash generation, and his very own [UEFIv2](https://www.powershellgallery.com/packages/UEFIv2) module:
https://oofhours.com/2022/08/02/connecting-the-dots-reverse-engineering-an-autopilot-hash/
https://oofhours.com/2020/11/25/geeking-out-with-uefi-again/

I realize that SoftwareLicensingService does not work in WinPE, but if it's possible to somehow extract the ProductKeyID or ProductKeyPkPn, then there could be a lookup table to match the edition.

It is possible to extract the [license key in WinPE](https://gist.github.com/jonathanelbailey/78817a36121b231f94b5) using the oa3tool.exe and then converting HEX to ASCII, but that's not much help for identifying the edition.

**Comment by skyblaster** [comment]
Running the oa3tool in WinPE does indeed yield a ProductKeyPkPn value.

I then tried copying everything in C:\Windows\System32\spp\ from my Windows 11 host to WinPE (post boot), however, a subsequent run of oa3tool does not add the ProductKeyPkPn.

If there is the possibility for a straight lookup from ProductKeyPkPn to Windows SKU/Edition, I've yet to find it.
