### ISSUE TITLE
Support 23H3 for OSDCloud

### ISSUE THREAD

**Issue by AndreasTheDead** [OSDeploy/OSD#87]
Hey,
Microsoft released 23H2 and i wanted to update the iso we provide our onsite support for it, but currently we get an error when wanting to setup the USB.

![image](https://github.com/OSDeploy/OSD/assets/16037934/34dce0d7-21be-44ba-aa59-2cd978190d28)

Would it be posible to add support?

**Comment by OSDeploy** [comment]
I build the OS tables from WSUS Feature Updates, but Microsoft has released Windows 11 23H2 in WSUS as UUP files, so there isn't an ESD that works.  Working on a solution.

**Comment by mmeierm** [comment]
The guys over at the Windows on Raspberry Project even have a nice tool to find all the needed ESD Files in all versions and languages:
https://www.worproject.com/esd

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/19b6dfcb-068c-49f6-a173-aa9383a37bb4)

**Comment by AkosBakos** [comment]
The GitHub repo is updated, and if you overwrite your module with what is in GitHub, you'd see the changes and 23H2 works

https://x.com/adurrante/status/1732875065937612960?s=61&t=1wSFafsMtpHmKZa8At1KYw

**Comment by mmeierm** [comment]
Can confirm, 23H2 works just fine. Thank you so much.

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/2370032d-664f-440a-b7ad-368fdcf1f320)

![grafik](https://github.com/OSDeploy/OSD/assets/83367358/674e0d42-0c44-4c8c-8591-e2d14d3600f4)

**Comment by gwblok** [comment]
Updated OSD Module with 23H2

**Comment by AndreasTheDead** [comment]
Hey,
thanks for your work.

It seams like a OSDCloud USB can download 23H2 but i'm not able to download 23H2 via the `Update-OSDCloudUSB -OS` toggle. Am i doing something wrong?

**Comment by gwblok** [comment]
Thanks Andreas, I didn't realize that command was using different code 'under the hood'.  I should be able to resolve it when I get time, probably a Jan release.

**Comment by AndreasTheDead** [comment]
Okay, i think that should work, for myself aswell as the onsite guys who are using the tool for there stock devices.

Thanks for your fast reply, i wish you nice holidays and thanks for providing such a useful tool!

**Comment by gwblok** [comment]
Updated OSDCloudUSB.ps1 to work with the new OperatingSystem Catalog structure
Updated the Building of the Catalog to include older versions of Windows 10
Next Release of OSD should now include those enhancements / bug fixes.

**Comment by gwblok** [comment]
Please test.  If the functionality isn't working, reopen / comment, and I'll look into it further.
