### ISSUE TITLE
Missing driver catalog for Microsoft Surface Go 4

### ISSUE THREAD

**Issue by wphilipsen** [OSDeploy/OSD#93]
Hi

It seems the driver catalog for OSDCloud doesn't include Surface Go 4. Is it possible to add this device?
It continues to fail deploying as no drivers are found.

Thank you.

**Comment by gwblok** [comment]
You could try this: https://everydayintech.com/update-surface-driver-catalog-just-in-time/

**Comment by ajn142attamu** [comment]
@gwblok I believe this issue can be resolved/closed now, as https://github.com/OSDeploy/OSD/commit/ca6bfe1dfb740618f96fece680341297cb94a684 added Surface Go 4 drivers.

**Comment by gwblok** [comment]
Closing, as this has been added in the recent module.
